import assert from 'node:assert/strict';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';

// The catalog is generated by *booting* the tool list, so this file needs the
// same headless environment the other main-process tests use.
process.env.HIVE_DATA_DIR = mkdtempSync(join(tmpdir(), 'hive-catalog-'));
process.env.HIVE_CLI = '1';

const DOC = resolve(process.cwd(), 'docs/TOOL_CATALOG.md');
const NOTE = '<!-- Generated by `npm run docs:tools`. Do not edit by hand. -->';
const WRITE = process.argv.includes('--write');

async function main(): Promise<void> {
  const { listBuiltinTools } = await import('./builtin');
  const { renderCatalog } = await import('./catalog');

  const tools = listBuiltinTools();
  const rendered = renderCatalog(tools, NOTE) + '\n';

  // Every tool must describe itself and its parameters. An undocumented tool is
  // a tool the model has to guess at, so this fails rather than warns.
  for (const tool of tools) {
    assert.ok(tool.description.trim().length > 20, `${tool.name} needs a real description`);
    const props = (tool.parameters as { properties?: Record<string, { description?: string }> }).properties || {};
    for (const [param, spec] of Object.entries(props)) {
      // `path`, `cwd`, `content` and friends are self-describing; anything that
      // takes a flag or an option must say what it does.
      const selfEvident = ['path', 'cwd', 'content', 'pattern', 'command', 'url', 'message', 'source', 'prompt', 'text', 'name', 'description', 'query', 'scid', 'address', 'job_id', 'old_text', 'new_text'];
      if (selfEvident.includes(param)) continue;
      assert.ok((spec.description || '').trim().length > 0, `${tool.name}.${param} has no description`);
    }
  }

  if (WRITE) {
    writeFileSync(DOC, rendered, 'utf-8');
    console.log(`wrote ${DOC}`);
    return;
  }

  assert.ok(existsSync(DOC), `${DOC} is missing — run: npm run docs:tools`);
  const onDisk = readFileSync(DOC, 'utf-8');
  assert.equal(
    onDisk.trim(),
    rendered.trim(),
    'docs/TOOL_CATALOG.md is out of date with the booted tool schemas — run: npm run docs:tools'
  );
}

main()
  .then(() => { if (!WRITE) console.log('catalog.test.ts passed'); })
  .catch((err) => { console.error(err instanceof Error ? err.message : err); process.exit(1); });
