// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAllowedHost(arg1) {
  return window['go']['main']['App']['AddAllowedHost'](arg1);
}

export function AddContact(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddContact'](arg1, arg2, arg3);
}

export function AddSCIDToIndex(arg1) {
  return window['go']['main']['App']['AddSCIDToIndex'](arg1);
}

export function AddSearchExclusion(arg1) {
  return window['go']['main']['App']['AddSearchExclusion'](arg1);
}

export function AddTrackedToken(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddTrackedToken'](arg1, arg2, arg3);
}

export function ApproveWalletConnection() {
  return window['go']['main']['App']['ApproveWalletConnection']();
}

export function BatchDeployToSimulator(arg1) {
  return window['go']['main']['App']['BatchDeployToSimulator'](arg1);
}

export function BatchPrefetchFavorites(arg1, arg2) {
  return window['go']['main']['App']['BatchPrefetchFavorites'](arg1, arg2);
}

export function BuildRating(arg1, arg2) {
  return window['go']['main']['App']['BuildRating'](arg1, arg2);
}

export function CallXSWD(arg1) {
  return window['go']['main']['App']['CallXSWD'](arg1);
}

export function CancelRegistration() {
  return window['go']['main']['App']['CancelRegistration']();
}

export function CaptureSCState(arg1) {
  return window['go']['main']['App']['CaptureSCState'](arg1);
}

export function ChangeWalletPassword(arg1, arg2) {
  return window['go']['main']['App']['ChangeWalletPassword'](arg1, arg2);
}

export function CheckAllForUpdates() {
  return window['go']['main']['App']['CheckAllForUpdates']();
}

export function CheckAppFilter(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CheckAppFilter'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CheckAppForUpdate(arg1) {
  return window['go']['main']['App']['CheckAppForUpdate'](arg1);
}

export function CheckAppSupportsEpoch(arg1) {
  return window['go']['main']['App']['CheckAppSupportsEpoch'](arg1);
}

export function CheckBalanceForBatchDeployment(arg1, arg2, arg3) {
  return window['go']['main']['App']['CheckBalanceForBatchDeployment'](arg1, arg2, arg3);
}

export function CheckDerodStatus() {
  return window['go']['main']['App']['CheckDerodStatus']();
}

export function CleanGnomonDB(arg1) {
  return window['go']['main']['App']['CleanGnomonDB'](arg1);
}

export function ClearAppCache(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ClearAppCache'](arg1, arg2, arg3, arg4);
}

export function ClearAppFilterOverride(arg1) {
  return window['go']['main']['App']['ClearAppFilterOverride'](arg1);
}

export function ClearConnectionLog() {
  return window['go']['main']['App']['ClearConnectionLog']();
}

export function ClearConsoleLogs() {
  return window['go']['main']['App']['ClearConsoleLogs']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function ClearOfflineCache() {
  return window['go']['main']['App']['ClearOfflineCache']();
}

export function ClearRecentWallets() {
  return window['go']['main']['App']['ClearRecentWallets']();
}

export function ClearSearchExclusions() {
  return window['go']['main']['App']['ClearSearchExclusions']();
}

export function ClearStorageCategory(arg1) {
  return window['go']['main']['App']['ClearStorageCategory'](arg1);
}

export function ClearStorageTier(arg1) {
  return window['go']['main']['App']['ClearStorageTier'](arg1);
}

export function ClipboardClearIf(arg1) {
  return window['go']['main']['App']['ClipboardClearIf'](arg1);
}

export function CloneTELA(arg1, arg2) {
  return window['go']['main']['App']['CloneTELA'](arg1, arg2);
}

export function CloseWallet() {
  return window['go']['main']['App']['CloseWallet']();
}

export function CompareSCStateAtHeights(arg1, arg2, arg3) {
  return window['go']['main']['App']['CompareSCStateAtHeights'](arg1, arg2, arg3);
}

export function ConnectXSWD() {
  return window['go']['main']['App']['ConnectXSWD']();
}

export function ConstructFromShards(arg1) {
  return window['go']['main']['App']['ConstructFromShards'](arg1);
}

export function ConsumeLaunchURL() {
  return window['go']['main']['App']['ConsumeLaunchURL']();
}

export function CreatePaymentRequest(arg1, arg2) {
  return window['go']['main']['App']['CreatePaymentRequest'](arg1, arg2);
}

export function CreateWallet(arg1, arg2) {
  return window['go']['main']['App']['CreateWallet'](arg1, arg2);
}

export function DaemonGetBlockHeaderByHeight(arg1) {
  return window['go']['main']['App']['DaemonGetBlockHeaderByHeight'](arg1);
}

export function DaemonGetSC(arg1) {
  return window['go']['main']['App']['DaemonGetSC'](arg1);
}

export function DaemonGetTxPool() {
  return window['go']['main']['App']['DaemonGetTxPool']();
}

export function DecodeIntegratedAddress(arg1) {
  return window['go']['main']['App']['DecodeIntegratedAddress'](arg1);
}

export function DeleteContact(arg1) {
  return window['go']['main']['App']['DeleteContact'](arg1);
}

export function DeleteTransactionLabel(arg1) {
  return window['go']['main']['App']['DeleteTransactionLabel'](arg1);
}

export function DeleteVar(arg1, arg2) {
  return window['go']['main']['App']['DeleteVar'](arg1, arg2);
}

export function DeployTELABatch(arg1) {
  return window['go']['main']['App']['DeployTELABatch'](arg1);
}

export function DeployToSimulator(arg1) {
  return window['go']['main']['App']['DeployToSimulator'](arg1);
}

export function DetectDocTypes(arg1) {
  return window['go']['main']['App']['DetectDocTypes'](arg1);
}

export function DetectExistingBlockchain() {
  return window['go']['main']['App']['DetectExistingBlockchain']();
}

export function DetectRunningNode() {
  return window['go']['main']['App']['DetectRunningNode']();
}

export function DiffCachedVsOnChain(arg1) {
  return window['go']['main']['App']['DiffCachedVsOnChain'](arg1);
}

export function DiffCommits(arg1, arg2, arg3) {
  return window['go']['main']['App']['DiffCommits'](arg1, arg2, arg3);
}

export function DiffFiles(arg1, arg2) {
  return window['go']['main']['App']['DiffFiles'](arg1, arg2);
}

export function DiffSCIDs(arg1, arg2) {
  return window['go']['main']['App']['DiffSCIDs'](arg1, arg2);
}

export function DisconnectXSWD() {
  return window['go']['main']['App']['DisconnectXSWD']();
}

export function DislikeTELAApp(arg1) {
  return window['go']['main']['App']['DislikeTELAApp'](arg1);
}

export function EnsureGnomonRunning() {
  return window['go']['main']['App']['EnsureGnomonRunning']();
}

export function EstimateBatchGas(arg1) {
  return window['go']['main']['App']['EstimateBatchGas'](arg1);
}

export function EstimateSCGas(arg1, arg2, arg3) {
  return window['go']['main']['App']['EstimateSCGas'](arg1, arg2, arg3);
}

export function EstimateSimulatorGas(arg1) {
  return window['go']['main']['App']['EstimateSimulatorGas'](arg1);
}

export function EstimateSyncTime() {
  return window['go']['main']['App']['EstimateSyncTime']();
}

export function ExecuteSCViaXSWD(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteSCViaXSWD'](arg1, arg2, arg3);
}

export function FetchByDURL(arg1) {
  return window['go']['main']['App']['FetchByDURL'](arg1);
}

export function FetchSCID(arg1) {
  return window['go']['main']['App']['FetchSCID'](arg1);
}

export function FetchTELAContent(arg1) {
  return window['go']['main']['App']['FetchTELAContent'](arg1);
}

export function FilterSearchResults(arg1) {
  return window['go']['main']['App']['FilterSearchResults'](arg1);
}

export function FormatBlockAge(arg1) {
  return window['go']['main']['App']['FormatBlockAge'](arg1);
}

export function FundTestWallet(arg1, arg2) {
  return window['go']['main']['App']['FundTestWallet'](arg1, arg2);
}

export function GenerateSemanticLabel(arg1, arg2) {
  return window['go']['main']['App']['GenerateSemanticLabel'](arg1, arg2);
}

export function GenerateSubDirs(arg1, arg2) {
  return window['go']['main']['App']['GenerateSubDirs'](arg1, arg2);
}

export function GetActiveConnections() {
  return window['go']['main']['App']['GetActiveConnections']();
}

export function GetActiveXSWDConnections() {
  return window['go']['main']['App']['GetActiveXSWDConnections']();
}

export function GetAddress() {
  return window['go']['main']['App']['GetAddress']();
}

export function GetAddressBook() {
  return window['go']['main']['App']['GetAddressBook']();
}

export function GetAddressSCIDReferences(arg1) {
  return window['go']['main']['App']['GetAddressSCIDReferences'](arg1);
}

export function GetAllCachedNames() {
  return window['go']['main']['App']['GetAllCachedNames']();
}

export function GetAllClasses() {
  return window['go']['main']['App']['GetAllClasses']();
}

export function GetAllMODClasses() {
  return window['go']['main']['App']['GetAllMODClasses']();
}

export function GetAllSettings() {
  return window['go']['main']['App']['GetAllSettings']();
}

export function GetAllTags() {
  return window['go']['main']['App']['GetAllTags']();
}

export function GetAllTransactionLabels() {
  return window['go']['main']['App']['GetAllTransactionLabels']();
}

export function GetAppDetails(arg1) {
  return window['go']['main']['App']['GetAppDetails'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetAppRating(arg1) {
  return window['go']['main']['App']['GetAppRating'](arg1);
}

export function GetAvailableDOCTypes() {
  return window['go']['main']['App']['GetAvailableDOCTypes']();
}

export function GetAvailableNetworks() {
  return window['go']['main']['App']['GetAvailableNetworks']();
}

export function GetBalance() {
  return window['go']['main']['App']['GetBalance']();
}

export function GetBalanceAtHeight(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetBalanceAtHeight'](arg1, arg2, arg3);
}

export function GetBlock(arg1) {
  return window['go']['main']['App']['GetBlock'](arg1);
}

export function GetBlockByHash(arg1) {
  return window['go']['main']['App']['GetBlockByHash'](arg1);
}

export function GetBlockExtended(arg1) {
  return window['go']['main']['App']['GetBlockExtended'](arg1);
}

export function GetBlockchainStats() {
  return window['go']['main']['App']['GetBlockchainStats']();
}

export function GetCachedApps() {
  return window['go']['main']['App']['GetCachedApps']();
}

export function GetClonePath() {
  return window['go']['main']['App']['GetClonePath']();
}

export function GetCoinbaseMiner(arg1) {
  return window['go']['main']['App']['GetCoinbaseMiner'](arg1);
}

export function GetCommitContent(arg1, arg2) {
  return window['go']['main']['App']['GetCommitContent'](arg1, arg2);
}

export function GetCommitHistory(arg1) {
  return window['go']['main']['App']['GetCommitHistory'](arg1);
}

export function GetCommitHistoryWithLabels(arg1) {
  return window['go']['main']['App']['GetCommitHistoryWithLabels'](arg1);
}

export function GetConnectedApps() {
  return window['go']['main']['App']['GetConnectedApps']();
}

export function GetConnectionLog(arg1) {
  return window['go']['main']['App']['GetConnectionLog'](arg1);
}

export function GetConsoleLogs() {
  return window['go']['main']['App']['GetConsoleLogs']();
}

export function GetContentFilterConfig() {
  return window['go']['main']['App']['GetContentFilterConfig']();
}

export function GetContentFilterHistory(arg1) {
  return window['go']['main']['App']['GetContentFilterHistory'](arg1);
}

export function GetContentFilterRules() {
  return window['go']['main']['App']['GetContentFilterRules']();
}

export function GetContentFilterStats() {
  return window['go']['main']['App']['GetContentFilterStats']();
}

export function GetCurrentWalletPath() {
  return window['go']['main']['App']['GetCurrentWalletPath']();
}

export function GetDevSupportStats() {
  return window['go']['main']['App']['GetDevSupportStats']();
}

export function GetDevSupportStatus() {
  return window['go']['main']['App']['GetDevSupportStatus']();
}

export function GetDiscoveredApps() {
  return window['go']['main']['App']['GetDiscoveredApps']();
}

export function GetEpochAddressInfo() {
  return window['go']['main']['App']['GetEpochAddressInfo']();
}

export function GetEpochStats() {
  return window['go']['main']['App']['GetEpochStats']();
}

export function GetEpochSupportingApps() {
  return window['go']['main']['App']['GetEpochSupportingApps']();
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function GetGasEstimate(arg1) {
  return window['go']['main']['App']['GetGasEstimate'](arg1);
}

export function GetGnomonAutostart() {
  return window['go']['main']['App']['GetGnomonAutostart']();
}

export function GetGnomonStatus() {
  return window['go']['main']['App']['GetGnomonStatus']();
}

export function GetGnomonWSStatus() {
  return window['go']['main']['App']['GetGnomonWSStatus']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetINDEXInfo(arg1) {
  return window['go']['main']['App']['GetINDEXInfo'](arg1);
}

export function GetIntegratedAddress(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetIntegratedAddress'](arg1, arg2, arg3);
}

export function GetLiveStats() {
  return window['go']['main']['App']['GetLiveStats']();
}

export function GetLocalDevServerStatus() {
  return window['go']['main']['App']['GetLocalDevServerStatus']();
}

export function GetMODInfo(arg1) {
  return window['go']['main']['App']['GetMODInfo'](arg1);
}

export function GetMODsByClass(arg1) {
  return window['go']['main']['App']['GetMODsByClass'](arg1);
}

export function GetMODsList() {
  return window['go']['main']['App']['GetMODsList']();
}

export function GetMempoolExtended(arg1) {
  return window['go']['main']['App']['GetMempoolExtended'](arg1);
}

export function GetMempoolStats() {
  return window['go']['main']['App']['GetMempoolStats']();
}

export function GetMempoolTransactions() {
  return window['go']['main']['App']['GetMempoolTransactions']();
}

export function GetMetadataFiles(arg1) {
  return window['go']['main']['App']['GetMetadataFiles'](arg1);
}

export function GetMiningEarningsSummary() {
  return window['go']['main']['App']['GetMiningEarningsSummary']();
}

export function GetNRSCacheStats() {
  return window['go']['main']['App']['GetNRSCacheStats']();
}

export function GetNameForAddress(arg1) {
  return window['go']['main']['App']['GetNameForAddress'](arg1);
}

export function GetNameSuggestions(arg1) {
  return window['go']['main']['App']['GetNameSuggestions'](arg1);
}

export function GetNetworkFilterStatus() {
  return window['go']['main']['App']['GetNetworkFilterStatus']();
}

export function GetNetworkHealth() {
  return window['go']['main']['App']['GetNetworkHealth']();
}

export function GetNetworkInfo() {
  return window['go']['main']['App']['GetNetworkInfo']();
}

export function GetNetworkMode() {
  return window['go']['main']['App']['GetNetworkMode']();
}

export function GetNetworkStats() {
  return window['go']['main']['App']['GetNetworkStats']();
}

export function GetNodeAdvancedConfig() {
  return window['go']['main']['App']['GetNodeAdvancedConfig']();
}

export function GetNodeConfig() {
  return window['go']['main']['App']['GetNodeConfig']();
}

export function GetNodeLogs(arg1) {
  return window['go']['main']['App']['GetNodeLogs'](arg1);
}

export function GetNodeStatus() {
  return window['go']['main']['App']['GetNodeStatus']();
}

export function GetOfflineCacheStats() {
  return window['go']['main']['App']['GetOfflineCacheStats']();
}

export function GetPermissionTypes() {
  return window['go']['main']['App']['GetPermissionTypes']();
}

export function GetPersonalTransfers(arg1) {
  return window['go']['main']['App']['GetPersonalTransfers'](arg1);
}

export function GetPrivacyMode() {
  return window['go']['main']['App']['GetPrivacyMode']();
}

export function GetRandomSmartContracts(arg1) {
  return window['go']['main']['App']['GetRandomSmartContracts'](arg1);
}

export function GetRatingCategories() {
  return window['go']['main']['App']['GetRatingCategories']();
}

export function GetRatingDetails(arg1) {
  return window['go']['main']['App']['GetRatingDetails'](arg1);
}

export function GetRatingResultForSCID(arg1) {
  return window['go']['main']['App']['GetRatingResultForSCID'](arg1);
}

export function GetRatingsBreakdown(arg1) {
  return window['go']['main']['App']['GetRatingsBreakdown'](arg1);
}

export function GetRecentBlocks(arg1) {
  return window['go']['main']['App']['GetRecentBlocks'](arg1);
}

export function GetRecentWalletsWithInfo() {
  return window['go']['main']['App']['GetRecentWalletsWithInfo']();
}

export function GetRegistrationStatus() {
  return window['go']['main']['App']['GetRegistrationStatus']();
}

export function GetRingMembers(arg1) {
  return window['go']['main']['App']['GetRingMembers'](arg1);
}

export function GetSCChangeTimeline(arg1) {
  return window['go']['main']['App']['GetSCChangeTimeline'](arg1);
}

export function GetSCCode(arg1) {
  return window['go']['main']['App']['GetSCCode'](arg1);
}

export function GetSCIDMetadata(arg1) {
  return window['go']['main']['App']['GetSCIDMetadata'](arg1);
}

export function GetSCIDsByClass(arg1) {
  return window['go']['main']['App']['GetSCIDsByClass'](arg1);
}

export function GetSCIDsByTag(arg1) {
  return window['go']['main']['App']['GetSCIDsByTag'](arg1);
}

export function GetSCInfo(arg1) {
  return window['go']['main']['App']['GetSCInfo'](arg1);
}

export function GetSCInteractionHistory(arg1) {
  return window['go']['main']['App']['GetSCInteractionHistory'](arg1);
}

export function GetSCStateAtHeight(arg1, arg2) {
  return window['go']['main']['App']['GetSCStateAtHeight'](arg1, arg2);
}

export function GetSCStateHistory(arg1) {
  return window['go']['main']['App']['GetSCStateHistory'](arg1);
}

export function GetSCVariable(arg1, arg2) {
  return window['go']['main']['App']['GetSCVariable'](arg1, arg2);
}

export function GetSCVariables(arg1) {
  return window['go']['main']['App']['GetSCVariables'](arg1);
}

export function GetSearchExclusions() {
  return window['go']['main']['App']['GetSearchExclusions']();
}

export function GetSeedPhrase(arg1) {
  return window['go']['main']['App']['GetSeedPhrase'](arg1);
}

export function GetServerInfo(arg1) {
  return window['go']['main']['App']['GetServerInfo'](arg1);
}

export function GetServerPortRange() {
  return window['go']['main']['App']['GetServerPortRange']();
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function GetSimulatorDeploymentInfo() {
  return window['go']['main']['App']['GetSimulatorDeploymentInfo']();
}

export function GetSimulatorStatus() {
  return window['go']['main']['App']['GetSimulatorStatus']();
}

export function GetSimulatorTestWallet(arg1) {
  return window['go']['main']['App']['GetSimulatorTestWallet'](arg1);
}

export function GetSimulatorTestWallets() {
  return window['go']['main']['App']['GetSimulatorTestWallets']();
}

export function GetSimulatorWalletInfo() {
  return window['go']['main']['App']['GetSimulatorWalletInfo']();
}

export function GetSimulatorWalletStatus() {
  return window['go']['main']['App']['GetSimulatorWalletStatus']();
}

export function GetStorageUsage() {
  return window['go']['main']['App']['GetStorageUsage']();
}

export function GetSyncProgress() {
  return window['go']['main']['App']['GetSyncProgress']();
}

export function GetTELAAppsWithTags() {
  return window['go']['main']['App']['GetTELAAppsWithTags']();
}

export function GetTELALibraries() {
  return window['go']['main']['App']['GetTELALibraries']();
}

export function GetTagStats() {
  return window['go']['main']['App']['GetTagStats']();
}

export function GetTokenPortfolio() {
  return window['go']['main']['App']['GetTokenPortfolio']();
}

export function GetTrackedTokens() {
  return window['go']['main']['App']['GetTrackedTokens']();
}

export function GetTransaction(arg1) {
  return window['go']['main']['App']['GetTransaction'](arg1);
}

export function GetTransactionBasic(arg1) {
  return window['go']['main']['App']['GetTransactionBasic'](arg1);
}

export function GetTransactionExtended(arg1) {
  return window['go']['main']['App']['GetTransactionExtended'](arg1);
}

export function GetTransactionHistory(arg1) {
  return window['go']['main']['App']['GetTransactionHistory'](arg1);
}

export function GetTransactionLabel(arg1) {
  return window['go']['main']['App']['GetTransactionLabel'](arg1);
}

export function GetTransactionWithRings(arg1) {
  return window['go']['main']['App']['GetTransactionWithRings'](arg1);
}

export function GetWalletKeys(arg1) {
  return window['go']['main']['App']['GetWalletKeys'](arg1);
}

export function GetWalletMiningEarnings(arg1) {
  return window['go']['main']['App']['GetWalletMiningEarnings'](arg1);
}

export function GetWalletStatus() {
  return window['go']['main']['App']['GetWalletStatus']();
}

export function GetWalletSyncStatus() {
  return window['go']['main']['App']['GetWalletSyncStatus']();
}

export function GetWatchedSmartContracts() {
  return window['go']['main']['App']['GetWatchedSmartContracts']();
}

export function GetXSWDStatus() {
  return window['go']['main']['App']['GetXSWDStatus']();
}

export function GoBack() {
  return window['go']['main']['App']['GoBack']();
}

export function GoForward() {
  return window['go']['main']['App']['GoForward']();
}

export function GrantAppPermission(arg1, arg2, arg3) {
  return window['go']['main']['App']['GrantAppPermission'](arg1, arg2, arg3);
}

export function HandleEpochRequest(arg1, arg2) {
  return window['go']['main']['App']['HandleEpochRequest'](arg1, arg2);
}

export function InitializeEpoch() {
  return window['go']['main']['App']['InitializeEpoch']();
}

export function InstallDOC(arg1) {
  return window['go']['main']['App']['InstallDOC'](arg1);
}

export function InstallINDEX(arg1) {
  return window['go']['main']['App']['InstallINDEX'](arg1);
}

export function InstallSmartContract(arg1, arg2) {
  return window['go']['main']['App']['InstallSmartContract'](arg1, arg2);
}

export function InternalWalletCall(arg1, arg2, arg3) {
  return window['go']['main']['App']['InternalWalletCall'](arg1, arg2, arg3);
}

export function InvokeSCFromExplorer(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['InvokeSCFromExplorer'](arg1, arg2, arg3, arg4);
}

export function InvokeSCFunction(arg1) {
  return window['go']['main']['App']['InvokeSCFunction'](arg1);
}

export function IsAppCachedOffline(arg1) {
  return window['go']['main']['App']['IsAppCachedOffline'](arg1);
}

export function IsDevSupportEnabled() {
  return window['go']['main']['App']['IsDevSupportEnabled']();
}

export function IsDevSupportVerboseLogging() {
  return window['go']['main']['App']['IsDevSupportVerboseLogging']();
}

export function IsEpochActive() {
  return window['go']['main']['App']['IsEpochActive']();
}

export function IsEpochEnabled() {
  return window['go']['main']['App']['IsEpochEnabled']();
}

export function IsInSimulatorMode() {
  return window['go']['main']['App']['IsInSimulatorMode']();
}

export function IsRequestAllowed(arg1) {
  return window['go']['main']['App']['IsRequestAllowed'](arg1);
}

export function IsSimulatorReady() {
  return window['go']['main']['App']['IsSimulatorReady']();
}

export function IsSimulatorWalletRegistered() {
  return window['go']['main']['App']['IsSimulatorWalletRegistered']();
}

export function IsWalletOpen() {
  return window['go']['main']['App']['IsWalletOpen']();
}

export function LikeTELAApp(arg1) {
  return window['go']['main']['App']['LikeTELAApp'](arg1);
}

export function ListActiveServers() {
  return window['go']['main']['App']['ListActiveServers']();
}

export function ListDirectory(arg1) {
  return window['go']['main']['App']['ListDirectory'](arg1);
}

export function ListRecentWallets() {
  return window['go']['main']['App']['ListRecentWallets']();
}

export function LoadFilesFromPaths(arg1) {
  return window['go']['main']['App']['LoadFilesFromPaths'](arg1);
}

export function ManuallyAllowApp(arg1) {
  return window['go']['main']['App']['ManuallyAllowApp'](arg1);
}

export function ManuallyBlockApp(arg1) {
  return window['go']['main']['App']['ManuallyBlockApp'](arg1);
}

export function MoveFile(arg1, arg2) {
  return window['go']['main']['App']['MoveFile'](arg1, arg2);
}

export function Navigate(arg1) {
  return window['go']['main']['App']['Navigate'](arg1);
}

export function NotifyWizardComplete() {
  return window['go']['main']['App']['NotifyWizardComplete']();
}

export function OmniSearch(arg1) {
  return window['go']['main']['App']['OmniSearch'](arg1);
}

export function OpenSimulatorTestWallet(arg1) {
  return window['go']['main']['App']['OpenSimulatorTestWallet'](arg1);
}

export function OpenURLInBrowserIfAllowed(arg1) {
  return window['go']['main']['App']['OpenURLInBrowserIfAllowed'](arg1);
}

export function OpenWallet(arg1, arg2) {
  return window['go']['main']['App']['OpenWallet'](arg1, arg2);
}

export function ParseFolderForTELA(arg1) {
  return window['go']['main']['App']['ParseFolderForTELA'](arg1);
}

export function ParseRatingForUI(arg1) {
  return window['go']['main']['App']['ParseRatingForUI'](arg1);
}

export function ParseSCFunctions(arg1) {
  return window['go']['main']['App']['ParseSCFunctions'](arg1);
}

export function PrefetchApp(arg1) {
  return window['go']['main']['App']['PrefetchApp'](arg1);
}

export function PreflightExpand(arg1, arg2) {
  return window['go']['main']['App']['PreflightExpand'](arg1, arg2);
}

export function PrepareMODInstall(arg1, arg2) {
  return window['go']['main']['App']['PrepareMODInstall'](arg1, arg2);
}

export function PreviewDOC(arg1) {
  return window['go']['main']['App']['PreviewDOC'](arg1);
}

export function PreviewTELAApp(arg1) {
  return window['go']['main']['App']['PreviewTELAApp'](arg1);
}

export function QuickDeployFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['QuickDeployFile'](arg1, arg2, arg3);
}

export function RateTELA(arg1, arg2) {
  return window['go']['main']['App']['RateTELA'](arg1, arg2);
}

export function RateTELAApp(arg1, arg2) {
  return window['go']['main']['App']['RateTELAApp'](arg1, arg2);
}

export function ReadTextFile(arg1) {
  return window['go']['main']['App']['ReadTextFile'](arg1);
}

export function RebuildTagIndex() {
  return window['go']['main']['App']['RebuildTagIndex']();
}

export function RefreshLocalDevServer() {
  return window['go']['main']['App']['RefreshLocalDevServer']();
}

export function RefreshTestWalletBalance(arg1) {
  return window['go']['main']['App']['RefreshTestWalletBalance'](arg1);
}

export function RefreshTokenMetadata(arg1, arg2, arg3) {
  return window['go']['main']['App']['RefreshTokenMetadata'](arg1, arg2, arg3);
}

export function RefreshWatchedSCs() {
  return window['go']['main']['App']['RefreshWatchedSCs']();
}

export function RegisterWallet() {
  return window['go']['main']['App']['RegisterWallet']();
}

export function Reload() {
  return window['go']['main']['App']['Reload']();
}

export function RemoveAllowedHost(arg1) {
  return window['go']['main']['App']['RemoveAllowedHost'](arg1);
}

export function RemoveCachedApp(arg1) {
  return window['go']['main']['App']['RemoveCachedApp'](arg1);
}

export function RemoveFile(arg1) {
  return window['go']['main']['App']['RemoveFile'](arg1);
}

export function RemoveRecentWallet(arg1) {
  return window['go']['main']['App']['RemoveRecentWallet'](arg1);
}

export function RemoveSearchExclusion(arg1) {
  return window['go']['main']['App']['RemoveSearchExclusion'](arg1);
}

export function RemoveTrackedToken(arg1) {
  return window['go']['main']['App']['RemoveTrackedToken'](arg1);
}

export function RequestInterceptor(arg1) {
  return window['go']['main']['App']['RequestInterceptor'](arg1);
}

export function ResetHologram(arg1) {
  return window['go']['main']['App']['ResetHologram'](arg1);
}

export function ResetSimulator() {
  return window['go']['main']['App']['ResetSimulator']();
}

export function ResolveDeroName(arg1) {
  return window['go']['main']['App']['ResolveDeroName'](arg1);
}

export function ResolveDropPaths(arg1) {
  return window['go']['main']['App']['ResolveDropPaths'](arg1);
}

export function RespondToXSWDRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['RespondToXSWDRequest'](arg1, arg2, arg3);
}

export function RespondToXSWDRequestWithPermissions(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RespondToXSWDRequestWithPermissions'](arg1, arg2, arg3, arg4);
}

export function RestoreWallet(arg1, arg2, arg3) {
  return window['go']['main']['App']['RestoreWallet'](arg1, arg2, arg3);
}

export function ResyncGnomon() {
  return window['go']['main']['App']['ResyncGnomon']();
}

export function ResyncGnomonFromHeight(arg1) {
  return window['go']['main']['App']['ResyncGnomonFromHeight'](arg1);
}

export function RevokeAppPermission(arg1, arg2) {
  return window['go']['main']['App']['RevokeAppPermission'](arg1, arg2);
}

export function RevokeAppPermissions(arg1) {
  return window['go']['main']['App']['RevokeAppPermissions'](arg1);
}

export function RevokeXSWDConnection(arg1) {
  return window['go']['main']['App']['RevokeXSWDConnection'](arg1);
}

export function SaveBinaryFileWithDialog(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveBinaryFileWithDialog'](arg1, arg2, arg3, arg4);
}

export function SaveFileWithDialog(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveFileWithDialog'](arg1, arg2, arg3, arg4);
}

export function ScanFolder(arg1) {
  return window['go']['main']['App']['ScanFolder'](arg1);
}

export function ScanWalletForTokens() {
  return window['go']['main']['App']['ScanWalletForTokens']();
}

export function SearchAddress(arg1) {
  return window['go']['main']['App']['SearchAddress'](arg1);
}

export function SearchApps(arg1) {
  return window['go']['main']['App']['SearchApps'](arg1);
}

export function SearchByKey(arg1) {
  return window['go']['main']['App']['SearchByKey'](arg1);
}

export function SearchByValue(arg1) {
  return window['go']['main']['App']['SearchByValue'](arg1);
}

export function SearchCodeLine(arg1) {
  return window['go']['main']['App']['SearchCodeLine'](arg1);
}

export function SearchMyContent() {
  return window['go']['main']['App']['SearchMyContent']();
}

export function SearchMyDOCs(arg1) {
  return window['go']['main']['App']['SearchMyDOCs'](arg1);
}

export function SearchMyINDEXes() {
  return window['go']['main']['App']['SearchMyINDEXes']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectFileWithContent(arg1, arg2) {
  return window['go']['main']['App']['SelectFileWithContent'](arg1, arg2);
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SelectWalletFile() {
  return window['go']['main']['App']['SelectWalletFile']();
}

export function ServeLocalDirectory(arg1) {
  return window['go']['main']['App']['ServeLocalDirectory'](arg1);
}

export function ServeTELAContent(arg1) {
  return window['go']['main']['App']['ServeTELAContent'](arg1);
}

export function SetContentFilterConfig(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['SetContentFilterConfig'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function SetDevSupportEnabled(arg1) {
  return window['go']['main']['App']['SetDevSupportEnabled'](arg1);
}

export function SetDevSupportVerboseLogging(arg1) {
  return window['go']['main']['App']['SetDevSupportVerboseLogging'](arg1);
}

export function SetEpochConfig(arg1, arg2) {
  return window['go']['main']['App']['SetEpochConfig'](arg1, arg2);
}

export function SetEpochEnabled(arg1) {
  return window['go']['main']['App']['SetEpochEnabled'](arg1);
}

export function SetGnomonAutostart(arg1) {
  return window['go']['main']['App']['SetGnomonAutostart'](arg1);
}

export function SetMaxServers(arg1) {
  return window['go']['main']['App']['SetMaxServers'](arg1);
}

export function SetNetworkMode(arg1) {
  return window['go']['main']['App']['SetNetworkMode'](arg1);
}

export function SetNodeAdvancedConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetNodeAdvancedConfig'](arg1, arg2, arg3);
}

export function SetNodeConfig(arg1) {
  return window['go']['main']['App']['SetNodeConfig'](arg1);
}

export function SetNodePorts(arg1, arg2) {
  return window['go']['main']['App']['SetNodePorts'](arg1, arg2);
}

export function SetOfflineCacheEnabled(arg1) {
  return window['go']['main']['App']['SetOfflineCacheEnabled'](arg1);
}

export function SetPrivacyMode(arg1) {
  return window['go']['main']['App']['SetPrivacyMode'](arg1);
}

export function SetSearchMinLikes(arg1) {
  return window['go']['main']['App']['SetSearchMinLikes'](arg1);
}

export function SetServerPortStart(arg1) {
  return window['go']['main']['App']['SetServerPortStart'](arg1);
}

export function SetSetting(arg1) {
  return window['go']['main']['App']['SetSetting'](arg1);
}

export function SetTransactionLabel(arg1, arg2) {
  return window['go']['main']['App']['SetTransactionLabel'](arg1, arg2);
}

export function SetVar(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetVar'](arg1, arg2, arg3);
}

export function ShardFile(arg1, arg2) {
  return window['go']['main']['App']['ShardFile'](arg1, arg2);
}

export function ShutdownAllServers() {
  return window['go']['main']['App']['ShutdownAllServers']();
}

export function ShutdownEpoch() {
  return window['go']['main']['App']['ShutdownEpoch']();
}

export function ShutdownLocalServers() {
  return window['go']['main']['App']['ShutdownLocalServers']();
}

export function ShutdownServer(arg1) {
  return window['go']['main']['App']['ShutdownServer'](arg1);
}

export function ShutdownTELAServers() {
  return window['go']['main']['App']['ShutdownTELAServers']();
}

export function SignMessage(arg1) {
  return window['go']['main']['App']['SignMessage'](arg1);
}

export function SplitIntegratedAddress(arg1) {
  return window['go']['main']['App']['SplitIntegratedAddress'](arg1);
}

export function StartBlockMonitoring() {
  return window['go']['main']['App']['StartBlockMonitoring']();
}

export function StartEpochAddressMonitor() {
  return window['go']['main']['App']['StartEpochAddressMonitor']();
}

export function StartGnomon() {
  return window['go']['main']['App']['StartGnomon']();
}

export function StartGnomonWSServer(arg1) {
  return window['go']['main']['App']['StartGnomonWSServer'](arg1);
}

export function StartLocalDevServer(arg1) {
  return window['go']['main']['App']['StartLocalDevServer'](arg1);
}

export function StartNode(arg1) {
  return window['go']['main']['App']['StartNode'](arg1);
}

export function StartNodeWithNetwork(arg1, arg2) {
  return window['go']['main']['App']['StartNodeWithNetwork'](arg1, arg2);
}

export function StartSimulatorMode() {
  return window['go']['main']['App']['StartSimulatorMode']();
}

export function StartStatusBroadcast() {
  return window['go']['main']['App']['StartStatusBroadcast']();
}

export function StopBlockMonitoring() {
  return window['go']['main']['App']['StopBlockMonitoring']();
}

export function StopEpochAddressMonitor() {
  return window['go']['main']['App']['StopEpochAddressMonitor']();
}

export function StopGnomon() {
  return window['go']['main']['App']['StopGnomon']();
}

export function StopGnomonWSServer() {
  return window['go']['main']['App']['StopGnomonWSServer']();
}

export function StopLocalDevServer() {
  return window['go']['main']['App']['StopLocalDevServer']();
}

export function StopNode() {
  return window['go']['main']['App']['StopNode']();
}

export function StopSimulatorMode() {
  return window['go']['main']['App']['StopSimulatorMode']();
}

export function SubmitRatingWithPicker(arg1, arg2, arg3) {
  return window['go']['main']['App']['SubmitRatingWithPicker'](arg1, arg2, arg3);
}

export function SubscribeToBlockEvents() {
  return window['go']['main']['App']['SubscribeToBlockEvents']();
}

export function SubscribeToWalletEvents() {
  return window['go']['main']['App']['SubscribeToWalletEvents']();
}

export function SwitchWallet(arg1, arg2) {
  return window['go']['main']['App']['SwitchWallet'](arg1, arg2);
}

export function SyncSimulatorTestWallets() {
  return window['go']['main']['App']['SyncSimulatorTestWallets']();
}

export function SyncWallet() {
  return window['go']['main']['App']['SyncWallet']();
}

export function TestAndConnectEndpoint(arg1) {
  return window['go']['main']['App']['TestAndConnectEndpoint'](arg1);
}

export function Transfer(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Transfer'](arg1, arg2, arg3, arg4);
}

export function TransferToken(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['TransferToken'](arg1, arg2, arg3, arg4, arg5);
}

export function UnsubscribeFromEvents() {
  return window['go']['main']['App']['UnsubscribeFromEvents']();
}

export function UnwatchSmartContract(arg1) {
  return window['go']['main']['App']['UnwatchSmartContract'](arg1);
}

export function UpdateCachedApp(arg1) {
  return window['go']['main']['App']['UpdateCachedApp'](arg1);
}

export function UpdateContact(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateContact'](arg1, arg2, arg3, arg4);
}

export function UpdateINDEX(arg1, arg2) {
  return window['go']['main']['App']['UpdateINDEX'](arg1, arg2);
}

export function UseSimulatorWallet() {
  return window['go']['main']['App']['UseSimulatorWallet']();
}

export function ValidateProof(arg1) {
  return window['go']['main']['App']['ValidateProof'](arg1);
}

export function ValidateProofFull(arg1, arg2) {
  return window['go']['main']['App']['ValidateProofFull'](arg1, arg2);
}

export function ValidateSCCode(arg1) {
  return window['go']['main']['App']['ValidateSCCode'](arg1);
}

export function ValidateSenderProof(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ValidateSenderProof'](arg1, arg2, arg3, arg4, arg5);
}

export function VerifySignature(arg1) {
  return window['go']['main']['App']['VerifySignature'](arg1);
}

export function WatchSmartContract(arg1, arg2) {
  return window['go']['main']['App']['WatchSmartContract'](arg1, arg2);
}
