// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {walletapi} from '../models';
import {main} from '../models';

export function AddAllowedHost(arg1:string):Promise<Record<string, any>>;

export function AddContact(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function AddSCIDToIndex(arg1:string):Promise<Record<string, any>>;

export function AddSearchExclusion(arg1:string):Promise<Record<string, any>>;

export function AddTrackedToken(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function ApproveWalletConnection():Promise<Record<string, any>>;

export function BatchDeployToSimulator(arg1:string):Promise<Record<string, any>>;

export function BatchPrefetchFavorites(arg1:Array<Record<string, any>>,arg2:number):Promise<Record<string, any>>;

export function BuildRating(arg1:number,arg2:number):Promise<Record<string, any>>;

export function CallXSWD(arg1:string):Promise<Record<string, any>>;

export function CancelRegistration():Promise<Record<string, any>>;

export function CaptureSCState(arg1:string):Promise<Record<string, any>>;

export function ChangeWalletPassword(arg1:string,arg2:string):Promise<Record<string, any>>;

export function CheckAllForUpdates():Promise<Record<string, any>>;

export function CheckAppFilter(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number,arg7:boolean):Promise<Record<string, any>>;

export function CheckAppForUpdate(arg1:string):Promise<Record<string, any>>;

export function CheckAppSupportsEpoch(arg1:string):Promise<Record<string, any>>;

export function CheckBalanceForBatchDeployment(arg1:walletapi.Wallet_Disk,arg2:number,arg3:boolean):Promise<boolean>;

export function CheckDerodStatus():Promise<Record<string, any>>;

export function CleanGnomonDB(arg1:string):Promise<Record<string, any>>;

export function ClearAppCache(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<Record<string, any>>;

export function ClearAppFilterOverride(arg1:string):Promise<Record<string, any>>;

export function ClearConnectionLog():Promise<Record<string, any>>;

export function ClearConsoleLogs():Promise<Record<string, any>>;

export function ClearHistory():Promise<Record<string, any>>;

export function ClearOfflineCache():Promise<Record<string, any>>;

export function ClearRecentWallets():Promise<Record<string, any>>;

export function ClearSearchExclusions():Promise<Record<string, any>>;

export function ClearStorageCategory(arg1:string):Promise<Record<string, any>>;

export function ClearStorageTier(arg1:string):Promise<Record<string, any>>;

export function ClipboardClearIf(arg1:string):Promise<Record<string, any>>;

export function CloneTELA(arg1:string,arg2:boolean):Promise<Record<string, any>>;

export function CloseWallet():Promise<Record<string, any>>;

export function CompareSCStateAtHeights(arg1:string,arg2:number,arg3:number):Promise<Record<string, any>>;

export function ConnectXSWD():Promise<Record<string, any>>;

export function ConstructFromShards(arg1:string):Promise<Record<string, any>>;

export function ConsumeLaunchURL():Promise<string>;

export function CreatePaymentRequest(arg1:number,arg2:string):Promise<Record<string, any>>;

export function CreateWallet(arg1:string,arg2:string):Promise<Record<string, any>>;

export function DaemonGetBlockHeaderByHeight(arg1:number):Promise<Record<string, any>>;

export function DaemonGetSC(arg1:string):Promise<Record<string, any>>;

export function DaemonGetTxPool():Promise<Record<string, any>>;

export function DecodeIntegratedAddress(arg1:string):Promise<Record<string, any>>;

export function DeleteContact(arg1:string):Promise<Record<string, any>>;

export function DeleteTransactionLabel(arg1:string):Promise<Record<string, any>>;

export function DeleteVar(arg1:string,arg2:string):Promise<Record<string, any>>;

export function DeployTELABatch(arg1:string):Promise<Record<string, any>>;

export function DeployToSimulator(arg1:string):Promise<Record<string, any>>;

export function DetectDocTypes(arg1:string):Promise<Record<string, any>>;

export function DetectExistingBlockchain():Promise<Record<string, any>>;

export function DetectRunningNode():Promise<Record<string, any>>;

export function DiffCachedVsOnChain(arg1:string):Promise<Record<string, any>>;

export function DiffCommits(arg1:string,arg2:number,arg3:number):Promise<Record<string, any>>;

export function DiffFiles(arg1:string,arg2:string):Promise<Record<string, any>>;

export function DiffSCIDs(arg1:string,arg2:string):Promise<Record<string, any>>;

export function DisconnectXSWD():Promise<Record<string, any>>;

export function DislikeTELAApp(arg1:string):Promise<Record<string, any>>;

export function EnsureGnomonRunning():Promise<Record<string, any>>;

export function EstimateBatchGas(arg1:string):Promise<Record<string, any>>;

export function EstimateSCGas(arg1:string,arg2:string,arg3:Array<Record<string, any>>):Promise<Record<string, any>>;

export function EstimateSimulatorGas(arg1:string):Promise<Record<string, any>>;

export function EstimateSyncTime():Promise<Record<string, any>>;

export function ExecuteSCViaXSWD(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function FetchByDURL(arg1:string):Promise<Record<string, any>>;

export function FetchSCID(arg1:string):Promise<Record<string, any>>;

export function FetchTELAContent(arg1:string):Promise<main.TELAContent>;

export function FilterSearchResults(arg1:Array<Record<string, any>>):Promise<Array<Record<string, any>>>;

export function FormatBlockAge(arg1:number):Promise<string>;

export function FundTestWallet(arg1:number,arg2:number):Promise<Record<string, any>>;

export function GenerateSemanticLabel(arg1:string,arg2:number):Promise<string>;

export function GenerateSubDirs(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetActiveConnections():Promise<Record<string, any>>;

export function GetActiveXSWDConnections():Promise<Record<string, any>>;

export function GetAddress():Promise<Record<string, any>>;

export function GetAddressBook():Promise<Record<string, any>>;

export function GetAddressSCIDReferences(arg1:string):Promise<Record<string, any>>;

export function GetAllCachedNames():Promise<Record<string, any>>;

export function GetAllClasses():Promise<Record<string, any>>;

export function GetAllMODClasses():Promise<Record<string, any>>;

export function GetAllSettings():Promise<Record<string, any>>;

export function GetAllTags():Promise<Record<string, any>>;

export function GetAllTransactionLabels():Promise<Record<string, any>>;

export function GetAppDetails(arg1:string):Promise<Record<string, any>>;

export function GetAppInfo():Promise<Record<string, any>>;

export function GetAppRating(arg1:string):Promise<Record<string, any>>;

export function GetAvailableDOCTypes():Promise<Record<string, any>>;

export function GetAvailableNetworks():Promise<Record<string, any>>;

export function GetBalance():Promise<Record<string, any>>;

export function GetBalanceAtHeight(arg1:string,arg2:number,arg3:string):Promise<Record<string, any>>;

export function GetBlock(arg1:number):Promise<Record<string, any>>;

export function GetBlockByHash(arg1:string):Promise<Record<string, any>>;

export function GetBlockExtended(arg1:string):Promise<Record<string, any>>;

export function GetBlockchainStats():Promise<Record<string, any>>;

export function GetCachedApps():Promise<Record<string, any>>;

export function GetClonePath():Promise<string>;

export function GetCoinbaseMiner(arg1:string):Promise<Record<string, any>>;

export function GetCommitContent(arg1:string,arg2:number):Promise<Record<string, any>>;

export function GetCommitHistory(arg1:string):Promise<Record<string, any>>;

export function GetCommitHistoryWithLabels(arg1:string):Promise<Record<string, any>>;

export function GetConnectedApps():Promise<Array<Record<string, any>>>;

export function GetConnectionLog(arg1:number):Promise<Record<string, any>>;

export function GetConsoleLogs():Promise<Array<main.ConsoleLog>>;

export function GetContentFilterConfig():Promise<Record<string, any>>;

export function GetContentFilterHistory(arg1:number):Promise<Record<string, any>>;

export function GetContentFilterRules():Promise<Record<string, any>>;

export function GetContentFilterStats():Promise<Record<string, any>>;

export function GetCurrentWalletPath():Promise<string>;

export function GetCypherpunkMode():Promise<boolean>;

export function GetDevSupportStats():Promise<Record<string, any>>;

export function GetDevSupportStatus():Promise<Record<string, any>>;

export function GetDiscoveredApps():Promise<Record<string, any>>;

export function GetEpochAddressInfo():Promise<Record<string, any>>;

export function GetEpochStats():Promise<Record<string, any>>;

export function GetEpochSupportingApps():Promise<Record<string, any>>;

export function GetFileInfo(arg1:string):Promise<Record<string, any>>;

export function GetGasEstimate(arg1:string):Promise<Record<string, any>>;

export function GetGnomonAutostart():Promise<boolean>;

export function GetGnomonStatus():Promise<Record<string, any>>;

export function GetGnomonWSStatus():Promise<Record<string, any>>;

export function GetHistory():Promise<Array<string>>;

export function GetINDEXInfo(arg1:string):Promise<Record<string, any>>;

export function GetIntegratedAddress(arg1:number,arg2:string,arg3:number):Promise<Record<string, any>>;

export function GetLiveStats():Promise<Record<string, any>>;

export function GetLocalDevServerStatus():Promise<Record<string, any>>;

export function GetMODInfo(arg1:string):Promise<Record<string, any>>;

export function GetMODsByClass(arg1:string):Promise<Record<string, any>>;

export function GetMODsList():Promise<Record<string, any>>;

export function GetMempoolExtended(arg1:number):Promise<Record<string, any>>;

export function GetMempoolStats():Promise<Record<string, any>>;

export function GetMempoolTransactions():Promise<Record<string, any>>;

export function GetMetadataFiles(arg1:string):Promise<Record<string, any>>;

export function GetMiningEarningsSummary():Promise<Record<string, any>>;

export function GetNRSCacheStats():Promise<Record<string, any>>;

export function GetNameForAddress(arg1:string):Promise<Record<string, any>>;

export function GetNameSuggestions(arg1:string):Promise<Record<string, any>>;

export function GetNetworkFilterStatus():Promise<Record<string, any>>;

export function GetNetworkHealth():Promise<Record<string, any>>;

export function GetNetworkInfo():Promise<Record<string, any>>;

export function GetNetworkMode():Promise<Record<string, any>>;

export function GetNetworkStats():Promise<Record<string, any>>;

export function GetNodeAdvancedConfig():Promise<Record<string, any>>;

export function GetNodeConfig():Promise<Record<string, any>>;

export function GetNodeLogs(arg1:number):Promise<Record<string, any>>;

export function GetNodeStatus():Promise<Record<string, any>>;

export function GetOfflineCacheStats():Promise<Record<string, any>>;

export function GetPermissionTypes():Promise<Array<Record<string, any>>>;

export function GetPersonalTransfers(arg1:Record<string, any>):Promise<Record<string, any>>;

export function GetRandomSmartContracts(arg1:number):Promise<Record<string, any>>;

export function GetRatingCategories():Promise<Record<string, any>>;

export function GetRatingDetails(arg1:number):Promise<Record<string, any>>;

export function GetRatingResultForSCID(arg1:string):Promise<main.RatingResult>;

export function GetRatingsBreakdown(arg1:string):Promise<Record<string, any>>;

export function GetRecentBlocks(arg1:number):Promise<Record<string, any>>;

export function GetRecentWalletsWithInfo():Promise<Array<main.WalletInfo>>;

export function GetRegistrationStatus():Promise<Record<string, any>>;

export function GetRingMembers(arg1:string):Promise<Record<string, any>>;

export function GetSCChangeTimeline(arg1:string):Promise<Record<string, any>>;

export function GetSCCode(arg1:string):Promise<Record<string, any>>;

export function GetSCIDMetadata(arg1:string):Promise<Record<string, any>>;

export function GetSCIDsByClass(arg1:string):Promise<Record<string, any>>;

export function GetSCIDsByTag(arg1:string):Promise<Record<string, any>>;

export function GetSCInfo(arg1:string):Promise<Record<string, any>>;

export function GetSCInteractionHistory(arg1:string):Promise<Record<string, any>>;

export function GetSCStateAtHeight(arg1:string,arg2:number):Promise<Record<string, any>>;

export function GetSCStateHistory(arg1:string):Promise<Record<string, any>>;

export function GetSCVariable(arg1:string,arg2:Array<string>):Promise<Record<string, any>>;

export function GetSCVariables(arg1:string):Promise<Record<string, any>>;

export function GetSearchExclusions():Promise<Record<string, any>>;

export function GetSeedPhrase(arg1:string):Promise<Record<string, any>>;

export function GetServerInfo(arg1:string):Promise<Record<string, any>>;

export function GetServerPortRange():Promise<Record<string, any>>;

export function GetSetting(arg1:string):Promise<any>;

export function GetSimulatorDeploymentInfo():Promise<Record<string, any>>;

export function GetSimulatorStatus():Promise<Record<string, any>>;

export function GetSimulatorTestWallet(arg1:number):Promise<Record<string, any>>;

export function GetSimulatorTestWallets():Promise<Record<string, any>>;

export function GetSimulatorWalletInfo():Promise<Record<string, any>>;

export function GetSimulatorWalletStatus():Promise<Record<string, any>>;

export function GetStorageUsage():Promise<main.StorageUsage>;

export function GetSyncProgress():Promise<Record<string, any>>;

export function GetTELAAppsWithTags():Promise<Record<string, any>>;

export function GetTELALibraries():Promise<Record<string, any>>;

export function GetTagStats():Promise<Record<string, any>>;

export function GetTokenPortfolio():Promise<Record<string, any>>;

export function GetTrackedTokens():Promise<Record<string, any>>;

export function GetTransaction(arg1:string):Promise<Record<string, any>>;

export function GetTransactionBasic(arg1:string):Promise<Record<string, any>>;

export function GetTransactionExtended(arg1:string):Promise<Record<string, any>>;

export function GetTransactionHistory(arg1:number):Promise<Record<string, any>>;

export function GetTransactionLabel(arg1:string):Promise<Record<string, any>>;

export function GetTransactionWithRings(arg1:string):Promise<Record<string, any>>;

export function GetWalletKeys(arg1:string):Promise<Record<string, any>>;

export function GetWalletMiningEarnings(arg1:number):Promise<Record<string, any>>;

export function GetWalletStatus():Promise<Record<string, any>>;

export function GetWalletSyncStatus():Promise<Record<string, any>>;

export function GetWatchedSmartContracts():Promise<Record<string, any>>;

export function GetXSWDStatus():Promise<Record<string, any>>;

export function GoBack():Promise<Record<string, any>>;

export function GoForward():Promise<Record<string, any>>;

export function GrantAppPermission(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function HandleEpochRequest(arg1:number,arg2:string):Promise<Record<string, any>>;

export function InitializeEpoch():Promise<Record<string, any>>;

export function InstallDOC(arg1:string):Promise<Record<string, any>>;

export function InstallINDEX(arg1:string):Promise<Record<string, any>>;

export function InstallSmartContract(arg1:string,arg2:boolean):Promise<Record<string, any>>;

export function InternalWalletCall(arg1:string,arg2:Record<string, any>,arg3:string):Promise<Record<string, any>>;

export function InvokeSCFromExplorer(arg1:string,arg2:string,arg3:Array<Record<string, any>>,arg4:number):Promise<Record<string, any>>;

export function InvokeSCFunction(arg1:string):Promise<Record<string, any>>;

export function IsAppCachedOffline(arg1:string):Promise<Record<string, any>>;

export function IsDevSupportEnabled():Promise<boolean>;

export function IsDevSupportVerboseLogging():Promise<boolean>;

export function IsEpochActive():Promise<boolean>;

export function IsEpochEnabled():Promise<boolean>;

export function IsInSimulatorMode():Promise<boolean>;

export function IsRequestAllowed(arg1:string):Promise<Record<string, any>>;

export function IsSimulatorReady():Promise<Record<string, any>>;

export function IsSimulatorWalletRegistered():Promise<Record<string, any>>;

export function IsWalletOpen():Promise<boolean>;

export function LikeTELAApp(arg1:string):Promise<Record<string, any>>;

export function ListActiveServers():Promise<Record<string, any>>;

export function ListDirectory(arg1:string):Promise<Record<string, any>>;

export function ListRecentWallets():Promise<Array<string>>;

export function LoadFilesFromPaths(arg1:Array<string>):Promise<Record<string, any>>;

export function ManuallyAllowApp(arg1:string):Promise<Record<string, any>>;

export function ManuallyBlockApp(arg1:string):Promise<Record<string, any>>;

export function MoveFile(arg1:string,arg2:string):Promise<Record<string, any>>;

export function Navigate(arg1:string):Promise<Record<string, any>>;

export function NotifyWizardComplete():Promise<void>;

export function OmniSearch(arg1:string):Promise<main.SearchResult>;

export function OpenSimulatorTestWallet(arg1:number):Promise<Record<string, any>>;

export function OpenURLInBrowserIfAllowed(arg1:string):Promise<Record<string, any>>;

export function OpenWallet(arg1:string,arg2:string):Promise<Record<string, any>>;

export function ParseFolderForTELA(arg1:string):Promise<Record<string, any>>;

export function ParseRatingForUI(arg1:number):Promise<Record<string, any>>;

export function ParseSCFunctions(arg1:string):Promise<Record<string, any>>;

export function PrefetchApp(arg1:string):Promise<Record<string, any>>;

export function PreflightExpand(arg1:string,arg2:string):Promise<Record<string, any>>;

export function PrepareMODInstall(arg1:string,arg2:string):Promise<Record<string, any>>;

export function PreviewDOC(arg1:string):Promise<Record<string, any>>;

export function PreviewTELAApp(arg1:string):Promise<Record<string, any>>;

export function QuickDeployFile(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function RateTELA(arg1:string,arg2:number):Promise<Record<string, any>>;

export function RateTELAApp(arg1:string,arg2:number):Promise<Record<string, any>>;

export function ReadTextFile(arg1:string):Promise<Record<string, any>>;

export function RebuildTagIndex():Promise<Record<string, any>>;

export function RefreshLocalDevServer():Promise<Record<string, any>>;

export function RefreshTestWalletBalance(arg1:number):Promise<Record<string, any>>;

export function RefreshWatchedSCs():Promise<Record<string, any>>;

export function RegisterWallet():Promise<Record<string, any>>;

export function Reload():Promise<Record<string, any>>;

export function RemoveAllowedHost(arg1:string):Promise<Record<string, any>>;

export function RemoveCachedApp(arg1:string):Promise<Record<string, any>>;

export function RemoveFile(arg1:string):Promise<Record<string, any>>;

export function RemoveRecentWallet(arg1:string):Promise<Record<string, any>>;

export function RemoveSearchExclusion(arg1:string):Promise<Record<string, any>>;

export function RemoveTrackedToken(arg1:string):Promise<Record<string, any>>;

export function RequestInterceptor(arg1:string):Promise<Record<string, any>>;

export function ResetHologram(arg1:string):Promise<Record<string, any>>;

export function ResetSimulator():Promise<Record<string, any>>;

export function ResolveDeroName(arg1:string):Promise<Record<string, any>>;

export function ResolveDropPaths(arg1:Array<string>):Promise<Record<string, any>>;

export function RespondToXSWDRequest(arg1:string,arg2:boolean,arg3:string):Promise<void>;

export function RespondToXSWDRequestWithPermissions(arg1:string,arg2:boolean,arg3:string,arg4:Array<string>):Promise<void>;

export function RestoreWallet(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function ResyncGnomon():Promise<Record<string, any>>;

export function ResyncGnomonFromHeight(arg1:number):Promise<Record<string, any>>;

export function RevokeAppPermission(arg1:string,arg2:string):Promise<Record<string, any>>;

export function RevokeAppPermissions(arg1:string):Promise<Record<string, any>>;

export function RevokeXSWDConnection(arg1:string):Promise<Record<string, any>>;

export function SaveBinaryFileWithDialog(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function SaveFileWithDialog(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function ScanFolder(arg1:string):Promise<Record<string, any>>;

export function ScanWalletForTokens():Promise<Record<string, any>>;

export function SearchAddress(arg1:string):Promise<Record<string, any>>;

export function SearchApps(arg1:string):Promise<Record<string, any>>;

export function SearchByKey(arg1:string):Promise<Record<string, any>>;

export function SearchByValue(arg1:string):Promise<Record<string, any>>;

export function SearchCodeLine(arg1:string):Promise<Record<string, any>>;

export function SearchMyContent():Promise<Record<string, any>>;

export function SearchMyDOCs(arg1:string):Promise<Record<string, any>>;

export function SearchMyINDEXes():Promise<Record<string, any>>;

export function SelectFile():Promise<string>;

export function SelectFileWithContent(arg1:string,arg2:string):Promise<Record<string, any>>;

export function SelectFiles():Promise<Record<string, any>>;

export function SelectFolder():Promise<string>;

export function SelectWalletFile():Promise<string>;

export function ServeLocalDirectory(arg1:string):Promise<Record<string, any>>;

export function ServeTELAContent(arg1:string):Promise<Record<string, any>>;

export function SetContentFilterConfig(arg1:boolean,arg2:number,arg3:boolean,arg4:boolean,arg5:boolean,arg6:boolean,arg7:string,arg8:number):Promise<Record<string, any>>;

export function SetCypherpunkMode(arg1:boolean):Promise<Record<string, any>>;

export function SetDevSupportEnabled(arg1:boolean):Promise<Record<string, any>>;

export function SetDevSupportVerboseLogging(arg1:boolean):Promise<Record<string, any>>;

export function SetEpochConfig(arg1:number,arg2:number):Promise<Record<string, any>>;

export function SetEpochEnabled(arg1:boolean):Promise<Record<string, any>>;

export function SetGnomonAutostart(arg1:boolean):Promise<Record<string, any>>;

export function SetMaxServers(arg1:number):Promise<Record<string, any>>;

export function SetNetworkMode(arg1:string):Promise<Record<string, any>>;

export function SetNodeAdvancedConfig(arg1:boolean,arg2:number,arg3:string):Promise<Record<string, any>>;

export function SetNodeConfig(arg1:Record<string, any>):Promise<Record<string, any>>;

export function SetNodePorts(arg1:number,arg2:number):Promise<Record<string, any>>;

export function SetOfflineCacheEnabled(arg1:boolean):Promise<Record<string, any>>;

export function SetSearchMinLikes(arg1:number):Promise<Record<string, any>>;

export function SetServerPortStart(arg1:number):Promise<Record<string, any>>;

export function SetSetting(arg1:string):Promise<Record<string, any>>;

export function SetTransactionLabel(arg1:string,arg2:string):Promise<Record<string, any>>;

export function SetVar(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function ShardFile(arg1:string,arg2:boolean):Promise<Record<string, any>>;

export function ShutdownAllServers():Promise<Record<string, any>>;

export function ShutdownEpoch():Promise<Record<string, any>>;

export function ShutdownLocalServers():Promise<Record<string, any>>;

export function ShutdownServer(arg1:string):Promise<Record<string, any>>;

export function ShutdownTELAServers():Promise<Record<string, any>>;

export function SignMessage(arg1:string):Promise<Record<string, any>>;

export function SplitIntegratedAddress(arg1:string):Promise<Record<string, any>>;

export function StartBlockMonitoring():Promise<void>;

export function StartEpochAddressMonitor():Promise<void>;

export function StartGnomon():Promise<Record<string, any>>;

export function StartGnomonWSServer(arg1:string):Promise<Record<string, any>>;

export function StartLocalDevServer(arg1:string):Promise<Record<string, any>>;

export function StartNode(arg1:string):Promise<Record<string, any>>;

export function StartNodeWithNetwork(arg1:string,arg2:string):Promise<Record<string, any>>;

export function StartSimulatorMode():Promise<Record<string, any>>;

export function StartStatusBroadcast():Promise<void>;

export function StopBlockMonitoring():Promise<void>;

export function StopEpochAddressMonitor():Promise<void>;

export function StopGnomon():Promise<Record<string, any>>;

export function StopGnomonWSServer():Promise<Record<string, any>>;

export function StopLocalDevServer():Promise<Record<string, any>>;

export function StopNode():Promise<Record<string, any>>;

export function StopSimulatorMode():Promise<Record<string, any>>;

export function SubmitRatingWithPicker(arg1:string,arg2:number,arg3:number):Promise<Record<string, any>>;

export function SubscribeToBlockEvents():Promise<Record<string, any>>;

export function SubscribeToWalletEvents():Promise<Record<string, any>>;

export function SwitchWallet(arg1:string,arg2:string):Promise<Record<string, any>>;

export function SyncSimulatorTestWallets():Promise<Record<string, any>>;

export function SyncWallet():Promise<Record<string, any>>;

export function TestAndConnectEndpoint(arg1:string):Promise<Record<string, any>>;

export function Transfer(arg1:string,arg2:number,arg3:string,arg4:number):Promise<Record<string, any>>;

export function TransferToken(arg1:string,arg2:string,arg3:number,arg4:string,arg5:number):Promise<Record<string, any>>;

export function UnsubscribeFromEvents():Promise<void>;

export function UnwatchSmartContract(arg1:string):Promise<Record<string, any>>;

export function UpdateCachedApp(arg1:string):Promise<Record<string, any>>;

export function UpdateContact(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function UpdateINDEX(arg1:string,arg2:string):Promise<Record<string, any>>;

export function UseSimulatorWallet():Promise<Record<string, any>>;

export function ValidateProof(arg1:string):Promise<Record<string, any>>;

export function ValidateProofFull(arg1:string,arg2:string):Promise<Record<string, any>>;

export function ValidateSCCode(arg1:string):Promise<Record<string, any>>;

export function ValidateSenderProof(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string):Promise<Record<string, any>>;

export function VerifySignature(arg1:string):Promise<Record<string, any>>;

export function WatchSmartContract(arg1:string,arg2:string):Promise<Record<string, any>>;
